---
core:
    num_workers: 10


inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "/home/ipvzero/Nornir-Blog/hosts.yaml"
        group_file: "/home/ipvzero/Nornir-Blog/groups.yaml"
        defaults_file: "/home/ipvzero/Nornir-Blog/defaults.yaml"
