---


R1:
    hostname: 192.168.31.11
    groups:
        - cisco_group
    data:
        domain: ipvzero

R2:
    hostname: 192.168.31.12
    groups:
        - cisco_group
    data:
        domain: ipvzero


R3:
    hostname: 192.168.31.13
    groups:
        - cisco_group
    data:
        domain: ipvzero


R4:
    hostname: 192.168.31.14
    groups:
        - cisco_group
    data:
        domain: ipvzero


R5:
    hostname: 192.168.31.15
    groups:
        - cisco_group
    data:
        domain: ipvzero


R6:
    hostname: 192.168.31.16
    groups:
        - cisco_group
    data:
        domain: ipvzero


R7:
    hostname: 192.168.31.17
    groups:
        - cisco_group
    data:
        domain: ipvzero


R8:
    hostname: 192.168.31.18
    groups:
        - cisco_group
    data:
        domain: ipvzero
